# Generated by Django 6.0.3 on 2026-10-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
